import type { Metadata } from "next";
import localfont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const syber = localfont({
  src: [
    {
      path: "../public/fonts/Neo-Syber-Italic.ttf",
      weight: "1000",
    },
  ],
  variable: "--font-syber",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${syber.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
